name: DAST

on: workflow_call

defaults:
  run:
    shell: bash

jobs:
  config_git:
    name: 'config_git'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"

      - name: Cache Git Config
        uses: actions/cache@v4
        with:
          path: /home/runner/.gitconfig
          key: git-config

  zap_baseline:
    name: 'zap_baseline_scan'
    runs-on: ubuntu-latest
    needs: config_git

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Restore Git Config
        uses: actions/cache@v4
        with:
          path: /home/runner/.gitconfig
          key: git-config

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.TOKEN_GIT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://hml-tcc-password-manager.vercel.app'
          cmd_options: >
            - a
            - j
            - m 10
          allow_issue_writing: 'true'
          artifact_name: 'zap_baseline_scan'

      - name: Upload Zap Baseline Scan Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: zap_baseline_scan
          path: |
            ${{ github.workspace }}/report_html.html
            ${{ github.workspace }}/report_md.md
            ${{ github.workspace }}/report_json.json

      - name: Save ZAP Baseline Scan Reports
        if: always()
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}
          NAME_REPO_GIT: ${{ secrets.NAME_REPO_GIT }}
          TOOL_NAME: zap_baseline_scan
          REPORT_FORMAT: json
          REPORT_NAME: report_json
        run: |
          cd scripts
          chmod +x save_report.sh
          ./save_report.sh $GITHUB_WORKSPACE "${{github.event.repository.name }}" "${{ github.ref_name }}"

  zap_full_scan:    
    name: 'zap_full_scan'
    runs-on: ubuntu-latest
    needs: config_git

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Git Config
        uses: actions/cache@v4
        with:
          path: /home/runner/.gitconfig
          key: git-config
  
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.TOKEN_GIT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://hml-tcc-password-manager.vercel.app'
          cmd_options: >
            - j 
            - a
            - m 10
          allow_issue_writing: 'true'
          artifact_name: 'zap_full_scan'

      - name: Upload Zap Full Scan Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: zap_full_scan
          path: |
            ${{ github.workspace }}/report_html.html
            ${{ github.workspace }}/report_md.md
            ${{ github.workspace }}/report_json.json

      - name: Save ZAP Full Scan Reports
        if: always()
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}
          NAME_REPO_GIT: ${{ secrets.NAME_REPO_GIT }}
          TOOL_NAME: zap_full_scan
          REPORT_FORMAT: json
          REPORT_NAME: report_json
        run: |
          cd scripts
          chmod +x save_report.sh
          ./save_report.sh $GITHUB_WORKSPACE "${{github.event.repository.name }}" "${{ github.ref_name }}" 
    
  nikto:
    name: 'nikto'
    runs-on: ubuntu-latest
    needs: config_git

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Git Config
        uses: actions/cache@v4
        with:
          path: /home/runner/.gitconfig
          key: git-config

      - name: Create nikto report file
        run: |
          touch ${{ github.workspace }}/nikto_out.json
          chmod o+w ${{ github.workspace }}/nikto_out.json
          chmod g+w ${{ github.workspace }}/nikto_out.json

      - name: Find absolute path of nikto_out.json
        id: find_file_path
        run: |
          file_path=$(realpath nikto_out.json)
          echo "FILE_PATH=$file_path" >> $GITHUB_ENV

      - name: Scan with nikto
        uses: thereisnotime/action-nikto@master
        with:
          url: "https://hml-tcc-password-manager.vercel.app/"
          additional_args: "-Option FAILURES=0 -o $FILE_PATH -Format json"
        continue-on-error: true

      - name: Scan with nikto
        uses: thereisnotime/action-nikto@master
        with:
          url: "https://hml-tcc-password-manager.vercel.app/"
          additional_args: "-v ${{github.workspace}}:/tmp -Option FAILURES=0 -o /tmp/nikto_out.html -Format html"
        continue-on-error: true

      - name: Upload Nikto Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: ${{ runner.temp }}/nikto_out.json

      - name: Upload Nikto Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: nikto_out.html
          path: nikto_out.html
      
      - name: Save Nikto Report
        if: always()
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}
          NAME_REPO_GIT: ${{ secrets.NAME_REPO_GIT }}
          TOOL_NAME: nikto
          REPORT_FORMAT: json
          REPORT_NAME: nikto_out
        run: |
          cd scripts
          chmod +x save_report.sh
          ./save_report.sh $GITHUB_WORKSPACE "${{github.event.repository.name }}" "${{ github.ref_name }}"
    
